!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  _import_: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - PRINT-EDITION.docx
    task_name: _import_
    task_out: ./
enabled: true
language: Python
src_files:
- process_docx.py
target_dir: process_docx
