project:
  type: book
  output-dir: ../docs

execute: 
  execute: false

book:
  title: "Doing Computational Social Science<br>[The **Continuous Development** Edition]{.small}"
  author: "[John McLevey](https://www.johnmclevey.com/)<br>University of Waterloo"
  favicon: media/logo.png
  keyword: python, computational social science, data science, data engineering, research computing, bayesian inference, bayesian data analysis, generative modelling, probabilistic modelling, natural language processing, text analysis, network analysis, network science, simulation modelling, agent-based modelling
  url: https://www.johnmclevey.com/dcss-supplementary/
  sidebar: 
    background: "#F5F5F5"
    logo: media/logo.png
    search: true
  repo-url: https://github.com/UWNETLAB/dcss_supplementary
  repo-subdir: book
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  image: media/logo.png

  chapters:
    - index.qmd
    - 00-introduction.qmd
    - part: Research Computing
      chapters:
        - 01-getting-started.qmd
        - 02-python-101.qmd
        - 03-python-102.qmd
    - part: Obtaining Data
      chapters:
        - 04-sampling-and-survey-data.qmd # Harm reduction survey; European Values Survey; Chris Bail's work; Total survey error framework; Gelman XBox study
        - 05-web-data-apis.qmd # trace, found (Salganik)
        - 06-web-data-scraping.qmd
        - 07-audio-image-and-document-data.qmd # in development
    - part: Exploring Data # This whole section is being revised
      chapters:
        # Add workflow to the start of chapters 9, 11, 13
        - 08-processing-structured-data.qmd # redesign as survey / readymade data chapter?
        - 09-exploratory-data-analysis-and-visualization.qmd # redesign to be more purposeful and lead into latent factors and components
        - 10-association-and-latent-factors.qmd # update this chapter given other changes to the book narrative; hint forward to generative models
        - 11-text-as-data.qmd # redesign as "text as data" chapter? + content from the text EDA chapter
        - 12-text-similarity-and-latent-semantic-space.qmd # hint forward to generative models
        - 13-social-networks-and-relational-thinking.qmd # same pattern here as with other chapters; general introduction, then an EDA chapter; can centrality analysis stuff go in here, or should it be elsewhere?
        - 14-structural-similarity-and-latent-social-space.qmd
    - part: Prediction and Inference
      chapters:
        - 15-machine-and-statistical-learning.qmd # another mashup of chapters
        - 16-prediction.qmd
        - 17-probability.qmd
        - 18-credibility.qmd
        - 19-causality.qmd # NEW
    - part: Generative Modeling # Add measurement and missing data stuff throughout 
      chapters:
        - 20-linear-regression.qmd
        - 21-multilevel-regression-with-post-stratification.qmd
        - 22-generalized-linear-models.qmd # NEW
        - 23-causal-analysis.qmd # CHAPTER OR SECTION?
        - 24-latent-structure-networks.qmd # Nested SBMs
        - 25-latent-topics-text-lda.qmd # LDA models (+ STM if possible)
        - 26-complex-adaptive-systems.qmd
        - 27-developing-agent-based-models.qmd 
    - part: Deep Learning Demystified
      chapters:
        - 28-artificial-neural-networks-fnn-rnn-cnn.qmd # ANNs with layer-based architectures; FNNs, RNNs, and CNNs; # filter in some of the connectionist stuff 
        - 29-processing-natural-language-data-spacy.qmd # practical: Spacy and word vectors; link back to pre-processing and then mention that we generally don't need that with deep learning coming up; focus on vectors/embeddings, similarities, and named entity recognition maybe; # I think this spacy chapter could easily be combined with word vectors chapter (do all embeddings with spacy?) but weird to do things like lemmatization and so on here when I am not doing those with transformers? Or should I highlight other aspects of spacy such as similarity measures and so on? ; # modelling meaning, word2vec, and then contextual embeddings; drop TWEC
        - 30-transformers-self-attention.qmd # theory + practical: attention-based architecture; BERT, GPT, and so on; + transfer learning and fine-tuning; practical: Hugging Face models for sentiment analysis, named entity recognition, and so on # GESIS + print edition stuff + sentiment analysis chapter with Tyler
        - 31-latent-topics-text-transformers.qmd # practical: KeyBERT and BERTopic; Multi-modal stuff too 
    - part: Professional Responsibilities
      chapters:
        - 32-research-ethics-politics-and-practices.qmd
        - 33-next-steps.qmd
    - references.qmd  
    - acknowledgements.qmd
    - changelog.qmd
  appendices:
      - appendix-centrality-formulas.qmd
      - appendix-courses.qmd
      
bibliography: references.bib
    
    
format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"