project:
  type: book
  output-dir: ../docs

execute: 
  execute: false

book:
  title: "Doing Computational Social Science<br>[The **Continuous Development** Edition]{.small}"
  author: "[John McLevey](https://www.johnmclevey.com/)<br>University of Waterloo"
  favicon: figures/logo.png
  keyword: python, computational social science, data science, data engineering, research computing, bayesian inference, bayesian data analysis, generative modelling, probabilistic modelling, natural language processing, text analysis, network analysis, network science, simulation modelling, agent-based modelling
  url: https://www.johnmclevey.com/dcss-supplementary/
  sidebar: 
    background: "#F5F5F5"
    logo: figures/logo.png
    search: true
  repo-url: https://github.com/UWNETLAB/dcss_supplementary
  repo-subdir: book
  repo-branch: master
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  image: figures/logo.png

  chapters:
    - index.qmd
    - introduction.qmd
    - part: "**COMPUTING**"
      chapters:
        - setting-up.qmd
        - python-101.qmd
        - python-102.qmd
        - processing-data.qmd
    - part: "**WORKFLOW**"
      chapters:
        - mindful-modelling.qmd
        - iteration.qmd
    - part: "**DATA**"
      chapters:
        - survey-data.qmd
        - web-data-apis.qmd
        - web-data-scraping.qmd
        - audio-and-document-data.qmd
        - text-as-data.qmd
        - relational-data.qmd
    - part: "**DISCOVERY**"
      chapters:
        - exploratory-data-analysis.qmd
        - reduction-and-latent-dimensions.qmd
        - mapping-text.qmd
        - centrality.qmd
        - mapping-network-structure.qmd
    - part: "**PREDICTION & INFERENCE**"
      chapters:
        - supervised-learning.qmd
        - prediction-and-classification.qmd
        - causality.qmd
        - probability.qmd
        - credibility.qmd
        - measurement-and-missingness.qmd
    - part: "**MODELING**"
      chapters:
        - linear-regression.qmd
        - multilevel-regression.qmd
        - generalized-linear-models.qmd
        - structural-causal-models.qmd
        - modeling-texts-lda.qmd
        - modeling-networks.qmd
        - agent-based-models.qmd
        - diffusion-opinion-cultural-cognition.qmd
    - part: "**DEEP LEARNING**"
      chapters:
        - artificial-neural-networks-fnn-rnn-cnn.qmd
        - language-models-and-embeddings.qmd
        - transformer-revolution.qmd
        - modeling-text-transformer-topic-models.qmd
    - part: "**RESPONSIBILITIES**"
      chapters:
        - ethical-css.qmd
        - open-css.qmd
        - future-css.qmd
    - references.qmd
  # - appendices:
    - acknowledgements.qmd
    - _courses.qmd
bibliography: references.bib
    

format:
  html:
    theme: tufte
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"
    reference-location: margin
    citation-location: margin
  # pdf:
    # documentclass: tufte-book