# Acknowledgements  {.unnumbered}

## Acknowledgements for the Continuous Development Edition

To come. 

## Acknowledgements from the Print Edition

This book would not exist in its current form, or perhaps at all, without the support, advice, and contributions of a great many other people. I am extremely grateful to all of them.

First and foremost, thanks to my PhD students Pierson Browne, Tyler Crick, and Alexander (Sasha) Graham for their many contributions to this book, especially in the final 6 months of work, when all three made a series of invaluable contributions to the project. Pierson Browne constructed the datasets used in the Bayesian regression modelling chapters and was instrumental in the development of all Bayesian data analysis chapters. Similarly, Tyler Crick was instrumental in the development of the chapters on stochastic block models, generative topic models, word embeddings, and transformers. He also put considerable effort into cleaning the Enron communication network. Sasha Graham was instrumental in the development of the chapters on network analysis and research ethics, and helped track the many complex knowledge and skill dependencies that stretch across all 33 chapters. He also helped identify something on the order of 50,000 cuttable words as production deadlines loomed. Pierson, Tyler, and Sasha have improved this book immeasurably, and I am very grateful for it. Thanks to Laine Bourassa and Alec for tolerating the same sort of working-all-hours nonsense that my partner has tolerated for far too long, even though they should not have had to.

Secondly, thanks to Jillian Anderson for providing an extremely thorough technical review of the manuscript, especially given that the word count of the version she reviewed was closer to 300,000 than 200,000. She has improved the manuscript in many ways, including by sharing her thoughts on data science, machine learning, ethics, computation, and professional development in our many conversations over the years. I’m especially grateful for all the practical wisdom she shared while we were co-teaching at GESIS in Cologne in early 2020. Her experience and expertise has had a strong influence on how I’ve come to see the field.

I would like to thank the students who have worked in my research lab (Netlab) at the University of Waterloo over the years, and who have all been centrally involved in my own learning process in computational social science. In addition to Pierson, Tyler, Sasha, and Jillian (who is now a big data developer at Simon Fraser University), I’d like to thank Reid McIlroy-Young, Joel Becker, Mumtahin Monzoor, Tiffany Lin, Rachel Wood, Alex de Witt, Alexis Foss Hill, Steve McColl, Brittany Etmanski, and Evaleen Hellinga. Thanks also to ‘honorary’ members of the lab, Yasmin Koop-Monteiro, Adam Howe, and Francois Lapachelle from the University of British Columbia, and Yixi Yang from Memorial University.

Thank you to all the undergraduate and graduate students who have taken courses in computational social science with me at the University of Waterloo. There are far too many to name, but I am especially grateful to those students whose feedback and level of engagement has resulted in substantial improvements to the material in this book. Thanks especially to Michelle Ashburner, Silas Tsui, Sunny Luo, Zane Elias, Ben Ang, Cassidy Raynham, Stephanie Reimer Rempel, Jordan Klassen, David Borkenhagen, Emilie Caron, Khoa Tran, Tyler Kruger, Nate Flatch, and Terry Zhang. Similarly, I would like to thank participants in workshops I’ve taught with preliminary chapter drafts at the University of Waterloo, the University of British Columbia, and at GESIS Leibniz Institute for the Social Sciences in Cologne. In particular, I would like to thank Stijn Daenekindt, Jessica Herzing, Tina Kretshel, Janice Aurini, Ali Marin, Eugena Kwon, Xiaowei Li, and Soli Dubash.

Many colleagues and friends have improved the content in this book (sometimes even unwittingly) via conversation and in some cases directly commenting on chapter drafts. I am especially grateful to Allyson Stokes, Peter Carrington, Johan Koskinen, David Tindall, Anabel Quan-Haase, Lorien Jasny, Mario Diani, Tuomas Yla-Anttila, Antti Gronow, Lasse Folke-Henriksen, Andrew Osmond, Ian Milligan, Igor Grossman, Howard Ramos, Marlene Mauk, Rochelle Terman, Jennifer Earl, Tina Fetner, Heather Douglas, Bernie Hogan, Raphael Heiberger, Jan Riebling, Alix Rule, Bonnie Erickson, Qiang Fu, Luka Kronegger, Deena Abul Fottouh, Harry Collins, Rob Evans, Martin Innes, Kate Duart, Alun Preece, Darrin Durant, Martin Weinel, Nicky Priaulx, Nina Kolleck, Marty Cooke, Owen Gallupe, Vanessa Schweizer, Rob Gorbet, Katie Plaisance, Ed Jernigan, Rob Nolan, Rashmee Singh, and John Scott. Thanks also to the anonymous reviewers who provided extremely helpful comments on draft chapters.

Thanks to my colleagues in the Faculty of Environment (ENV) at the University of Waterloo for providing an intellectual home where interdisciplinary research and teaching is encouraged and valued. I’m especially grateful to the faculty, staff, and students in Knowledge Integration, who have led by interdisciplinary example, curious open-mindedness, and a willingness to slow down and learn from people who do things differently. Thanks also to my ENV friends and colleagues for providing inspiration and support, and for keeping things in perspective.

At Sage, I would like to thank Jai Seaman for believing in this project from the start and doing everything she could to support it, including during tough times when the work felt insurmountable. Jai's editorial experience, expertise, patience, and goodwill helped make a book out of a sprawling collection of chapters. Charlotte Bush similarly played a central role in making this project a reality, and I am thankful to her for her expertise and patience. Thanks to Ian Antcliff for expertly guiding the manuscript through the production process despite disruptions related to COVID-19, and to everyone who contributed to the production of the book despite the challenges of the pandemic.

Thanks to my endlessly patient and understanding partner Allyson Stokes. She has supported and improved this project in many ways over the years, both as a partner and intellectually as a fellow sociologist. Finally, thank you to my friends and family for all the support, love, and much-needed fun.

This book was written using a combination of markdon, LaTeX, and Python written using open source text editors and Jupyter Notebooks, with pandoc for document conversion, git for version control, and conda and Docker for virtualization. Thanks to the many people who develop and maintain these and other open source tools.
